joints:
  name:
    - right_arm_0_joint
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
  position:
    - 0.0
    - 0.5
    - 0.13
    - -1.57
    - 0.08
    - -0.5
    - 0.0

