allegro_hand_control:
  # List of topics
  topics:
    - allegroHand/lib_cmd : String
    - allegroHand/envelop_torque : Float32
  allegroHand/lib_cmd:
     'front': go_front
     'left': go_left
     'table': go_table
     'socket': go_socket
     'insert': insert
     'search': plug_search
     'stop': stop
     'pause': pause
     'disconnect': disconnect
     'joint imp': joint_imp
     'gravity': safe_grav_comp
     'print': print
  allegroHand/envelop_torque:
    set torque half: 0.5
