allegro_hand_control:
  # List of topics
  topics:
    - allegroHand/lib_cmd : String
  allegroHand/lib_cmd:
     'go front': go_front
     'go left': go_left
     'go to table': go_table
     'socket': go_socket
     'insert': insert
     'search': plug_search
     'stop': stop
     'pause': pause
     'okay disconnect': disconnect
     'gravity': grav_comp
     'print': print
     'impedance two': impedance_two
     'impedance five': impedance_five
     'reset bias': bias

